//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalDetail
    {
        public int CapitalDetailID { get; set; }
        public Nullable<System.DateTime> CapitalUseDate { get; set; }
        public Nullable<int> CapitalTypeID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Remarks { get; set; }
        public string SellBuyBillNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
