//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public Nullable<int> NoOfItem { get; set; }
        public Nullable<int> PurchaseRate { get; set; }
        public Nullable<int> SellingRate { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<bool> IsFastRunning { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
