//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryType
    {
        public int InventoryTypeId { get; set; }
        public string InventoryTypeName { get; set; }
        public string InventoryDescription { get; set; }
        public string UnitName { get; set; }
    }
}
