//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryOrderDetail
    {
        public int InventoryOrderDetailID { get; set; }
        public int InventoryTypeID { get; set; }
        public Nullable<int> PurchaseRate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TotalItemsCost { get; set; }
        public string VatNo { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> SaleRate { get; set; }
        public string BarcodeID { get; set; }
        public Nullable<int> InventoryOrderID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
