//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> AmountPaidDate { get; set; }
        public Nullable<int> WorkAssignID { get; set; }
        public Nullable<int> TotalAmountToPay { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public Nullable<int> RemainingAmount { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
