//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int SaleOrderID { get; set; }
        public string BillNo { get; set; }
        public string PersonName { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> RemainingAmount { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<System.DateTime> SaleOrderDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsMakingRequired { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
