//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAssignInventoryUsed
    {
        public int WorkAssignInventoryUsedID { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public Nullable<int> InventoryUsedCount { get; set; }
        public Nullable<int> WorkAssignID { get; set; }
        public Nullable<int> UnitID { get; set; }
    }
}
