//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int ChequeID { get; set; }
        public string PaymentBillNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDueDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> IsChequeClear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
