//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryManagementEntities : DbContext
    {
        public InventoryManagementEntities()
            : base("name=InventoryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DevelopmentWork> DevelopmentWorks { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<InventoryOrderDetail> InventoryOrderDetails { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WorkAssign> WorkAssigns { get; set; }
        public DbSet<WorkAssignInventoryUsed> WorkAssignInventoryUseds { get; set; }
        public DbSet<WorkType> WorkTypes { get; set; }
        public DbSet<InventoryType> InventoryTypes { get; set; }
        public DbSet<InventoryOrder> InventoryOrders { get; set; }
        public DbSet<SalesOrder> SalesOrders { get; set; }
        public DbSet<Cheque> Cheques { get; set; }
        public DbSet<Expense> Expenses { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Seller> Sellers { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<Salary> Salaries { get; set; }
    }
}
