//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopmentWork
    {
        public int DevelopmentWorkID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> InventoryTypeID { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string TopMeasurement { get; set; }
        public string BottomMeasurement { get; set; }
        public string DesignPhotoUrl { get; set; }
        public Nullable<int> WorkTypeID { get; set; }
        public Nullable<decimal> MakingCost { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
