//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryType
    {
        public int InventoryTypeId { get; set; }
        public string InventoryCode { get; set; }
        public string InventoryTypeName { get; set; }
        public Nullable<long> InventoryCount { get; set; }
        public string InventoryDescription { get; set; }
        public string UnitName { get; set; }
        public string VAT { get; set; }
        public Nullable<int> LowStockCount { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
        public Nullable<decimal> SellingRate { get; set; }
        public Nullable<bool> FastMoving { get; set; }
        public string RagNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
