//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryOrder
    {
        public int InventoryOrderID { get; set; }
        public string OwnBillNo { get; set; }
        public string PurchaseBillNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> AmountPaidDate { get; set; }
        public Nullable<decimal> TotalOrderAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
