//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAssign
    {
        public int WorkAssignID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> WorkTypeID { get; set; }
        public Nullable<int> WorkCount { get; set; }
        public Nullable<System.DateTime> WorkAssignDate { get; set; }
        public Nullable<System.DateTime> ExpectedCompletionDate { get; set; }
        public Nullable<int> CompletedCount { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> RemainingCost { get; set; }
    }
}
